'use strict';

/*
   Source of these data:
   - Unicode Common Locale Data Repository
     (http://cldr.unicode.org/index/charts)
   - Version 33 (https://unicode.org/cldr/charts/33/)

   How this source file was created:
   - wget https://unicode.org/Public/cldr/33/cldr-common-33.0.zip
   - unzip cldr-common-33.0.zip
   - $EDITOR ./common/main/de.xml
   - $EDITOR ./common/main/en.xml
   - search for <territories> with language codes
   - remove tags with "alt" property
   - place both lists (english and german) next to each other
   - remove "United Nations" and "Vereinigte Nationen"
   - replace "&amp;" with "&"
   - edit
 */

export default [
  { code: 'AC', english: 'Ascension Island',                       deutsch: 'Ascension' },
  { code: 'AD', english: 'Andorra',                                deutsch: 'Andorra' },
  { code: 'AE', english: 'United Arab Emirates',                   deutsch: 'Vereinigte Arabische Emirate' },
  { code: 'AF', english: 'Afghanistan',                            deutsch: 'Afghanistan' },
  { code: 'AG', english: 'Antigua & Barbuda',                      deutsch: 'Antigua und Barbuda' },
  { code: 'AI', english: 'Anguilla',                               deutsch: 'Anguilla' },
  { code: 'AL', english: 'Albania',                                deutsch: 'Albanien' },
  { code: 'AM', english: 'Armenia',                                deutsch: 'Armenien' },
  { code: 'AO', english: 'Angola',                                 deutsch: 'Angola' },
  { code: 'AQ', english: 'Antarctica',                             deutsch: 'Antarktis' },
  { code: 'AR', english: 'Argentina',                              deutsch: 'Argentinien' },
  { code: 'AS', english: 'American Samoa',                         deutsch: 'Amerikanisch-Samoa' },
  { code: 'AT', english: 'Austria',                                deutsch: 'Österreich' },
  { code: 'AU', english: 'Australia',                              deutsch: 'Australien' },
  { code: 'AW', english: 'Aruba',                                  deutsch: 'Aruba' },
  { code: 'AX', english: 'Åland Islands',                          deutsch: 'Ålandinseln' },
  { code: 'AZ', english: 'Azerbaijan',                             deutsch: 'Aserbaidschan' },
  { code: 'BA', english: 'Bosnia & Herzegovina',                   deutsch: 'Bosnien und Herzegowina' },
  { code: 'BB', english: 'Barbados',                               deutsch: 'Barbados' },
  { code: 'BD', english: 'Bangladesh',                             deutsch: 'Bangladesch' },
  { code: 'BE', english: 'Belgium',                                deutsch: 'Belgien' },
  { code: 'BF', english: 'Burkina Faso',                           deutsch: 'Burkina Faso' },
  { code: 'BG', english: 'Bulgaria',                               deutsch: 'Bulgarien' },
  { code: 'BH', english: 'Bahrain',                                deutsch: 'Bahrain' },
  { code: 'BI', english: 'Burundi',                                deutsch: 'Burundi' },
  { code: 'BJ', english: 'Benin',                                  deutsch: 'Benin' },
  { code: 'BL', english: 'St. Barthélemy',                         deutsch: 'St. Barthélemy' },
  { code: 'BM', english: 'Bermuda',                                deutsch: 'Bermuda' },
  { code: 'BN', english: 'Brunei',                                 deutsch: 'Brunei Darussalam' },
  { code: 'BO', english: 'Bolivia',                                deutsch: 'Bolivien' },
  { code: 'BQ', english: 'Caribbean Netherlands',                  deutsch: 'Bonaire, Sint Eustatius und Saba' },
  { code: 'BR', english: 'Brazil',                                 deutsch: 'Brasilien' },
  { code: 'BS', english: 'Bahamas',                                deutsch: 'Bahamas' },
  { code: 'BT', english: 'Bhutan',                                 deutsch: 'Bhutan' },
  { code: 'BV', english: 'Bouvet Island',                          deutsch: 'Bouvetinsel' },
  { code: 'BW', english: 'Botswana',                               deutsch: 'Botsuana' },
  { code: 'BY', english: 'Belarus',                                deutsch: 'Belarus' },
  { code: 'BZ', english: 'Belize',                                 deutsch: 'Belize' },
  { code: 'CA', english: 'Canada',                                 deutsch: 'Kanada' },
  { code: 'CC', english: 'Cocos (Keeling) Islands',                deutsch: 'Kokosinseln' },
  { code: 'CD', english: 'Congo - Kinshasa',                       deutsch: 'Kongo-Kinshasa' },
  { code: 'CF', english: 'Central African Republic',               deutsch: 'Zentralafrikanische Republik' },
  { code: 'CG', english: 'Congo - Brazzaville',                    deutsch: 'Kongo-Brazzaville' },
  { code: 'CH', english: 'Switzerland',                            deutsch: 'Schweiz' },
  { code: 'CI', english: 'Côte d’Ivoire',                          deutsch: 'Côte d’Ivoire' },
  { code: 'CK', english: 'Cook Islands',                           deutsch: 'Cookinseln' },
  { code: 'CL', english: 'Chile',                                  deutsch: 'Chile' },
  { code: 'CM', english: 'Cameroon',                               deutsch: 'Kamerun' },
  { code: 'CN', english: 'China',                                  deutsch: 'China' },
  { code: 'CO', english: 'Colombia',                               deutsch: 'Kolumbien' },
  { code: 'CP', english: 'Clipperton Island',                      deutsch: 'Clipperton-Insel' },
  { code: 'CR', english: 'Costa Rica',                             deutsch: 'Costa Rica' },
  { code: 'CU', english: 'Cuba',                                   deutsch: 'Kuba' },
  { code: 'CV', english: 'Cape Verde',                             deutsch: 'Cabo Verde' },
  { code: 'CW', english: 'Curaçao',                                deutsch: 'Curaçao' },
  { code: 'CX', english: 'Christmas Island',                       deutsch: 'Weihnachtsinsel' },
  { code: 'CY', english: 'Cyprus',                                 deutsch: 'Zypern' },
  { code: 'CZ', english: 'Czechia',                                deutsch: 'Tschechien' },
  { code: 'DE', english: 'Germany',                                deutsch: 'Deutschland' },
  { code: 'DG', english: 'Diego Garcia',                           deutsch: 'Diego Garcia' },
  { code: 'DJ', english: 'Djibouti',                               deutsch: 'Dschibuti' },
  { code: 'DK', english: 'Denmark',                                deutsch: 'Dänemark' },
  { code: 'DM', english: 'Dominica',                               deutsch: 'Dominica' },
  { code: 'DO', english: 'Dominican Republic',                     deutsch: 'Dominikanische Republik' },
  { code: 'DZ', english: 'Algeria',                                deutsch: 'Algerien' },
  { code: 'EA', english: 'Ceuta & Melilla',                        deutsch: 'Ceuta und Melilla' },
  { code: 'EC', english: 'Ecuador',                                deutsch: 'Ecuador' },
  { code: 'EE', english: 'Estonia',                                deutsch: 'Estland' },
  { code: 'EG', english: 'Egypt',                                  deutsch: 'Ägypten' },
  { code: 'EH', english: 'Western Sahara',                         deutsch: 'Westsahara' },
  { code: 'ER', english: 'Eritrea',                                deutsch: 'Eritrea' },
  { code: 'ES', english: 'Spain',                                  deutsch: 'Spanien' },
  { code: 'ET', english: 'Ethiopia',                               deutsch: 'Äthiopien' },
  { code: 'EU', english: 'European Union',                         deutsch: 'Europäische Union' },
  { code: 'EZ', english: 'Eurozone',                               deutsch: 'Eurozone' },
  { code: 'FI', english: 'Finland',                                deutsch: 'Finnland' },
  { code: 'FJ', english: 'Fiji',                                   deutsch: 'Fidschi' },
  { code: 'FK', english: 'Falkland Islands',                       deutsch: 'Falklandinseln' },
  { code: 'FM', english: 'Micronesia',                             deutsch: 'Mikronesien' },
  { code: 'FO', english: 'Faroe Islands',                          deutsch: 'Färöer' },
  { code: 'FR', english: 'France',                                 deutsch: 'Frankreich' },
  { code: 'GA', english: 'Gabon',                                  deutsch: 'Gabun' },
  { code: 'GB', english: 'United Kingdom',                         deutsch: 'Vereinigtes Königreich' },
  { code: 'GD', english: 'Grenada',                                deutsch: 'Grenada' },
  { code: 'GE', english: 'Georgia',                                deutsch: 'Georgien' },
  { code: 'GF', english: 'French Guiana',                          deutsch: 'Französisch-Guayana' },
  { code: 'GG', english: 'Guernsey',                               deutsch: 'Guernsey' },
  { code: 'GH', english: 'Ghana',                                  deutsch: 'Ghana' },
  { code: 'GI', english: 'Gibraltar',                              deutsch: 'Gibraltar' },
  { code: 'GL', english: 'Greenland',                              deutsch: 'Grönland' },
  { code: 'GM', english: 'Gambia',                                 deutsch: 'Gambia' },
  { code: 'GN', english: 'Guinea',                                 deutsch: 'Guinea' },
  { code: 'GP', english: 'Guadeloupe',                             deutsch: 'Guadeloupe' },
  { code: 'GQ', english: 'Equatorial Guinea',                      deutsch: 'Äquatorialguinea' },
  { code: 'GR', english: 'Greece',                                 deutsch: 'Griechenland' },
  { code: 'GS', english: 'South Georgia & South Sandwich Islands', deutsch: 'Südgeorgien und die Südlichen Sandwichinseln' },
  { code: 'GT', english: 'Guatemala',                              deutsch: 'Guatemala' },
  { code: 'GU', english: 'Guam',                                   deutsch: 'Guam' },
  { code: 'GW', english: 'Guinea-Bissau',                          deutsch: 'Guinea-Bissau' },
  { code: 'GY', english: 'Guyana',                                 deutsch: 'Guyana' },
  { code: 'HK', english: 'Hong Kong SAR China',                    deutsch: 'Sonderverwaltungsregion Hongkong' },
  { code: 'HM', english: 'Heard & McDonald Islands',               deutsch: 'Heard und McDonaldinseln' },
  { code: 'HN', english: 'Honduras',                               deutsch: 'Honduras' },
  { code: 'HR', english: 'Croatia',                                deutsch: 'Kroatien' },
  { code: 'HT', english: 'Haiti',                                  deutsch: 'Haiti' },
  { code: 'HU', english: 'Hungary',                                deutsch: 'Ungarn' },
  { code: 'IC', english: 'Canary Islands',                         deutsch: 'Kanarische Inseln' },
  { code: 'ID', english: 'Indonesia',                              deutsch: 'Indonesien' },
  { code: 'IE', english: 'Ireland',                                deutsch: 'Irland' },
  { code: 'IL', english: 'Israel',                                 deutsch: 'Israel' },
  { code: 'IM', english: 'Isle of Man',                            deutsch: 'Isle of Man' },
  { code: 'IN', english: 'India',                                  deutsch: 'Indien' },
  { code: 'IO', english: 'British Indian Ocean Territory',         deutsch: 'Britisches Territorium im Indischen Ozean' },
  { code: 'IQ', english: 'Iraq',                                   deutsch: 'Irak' },
  { code: 'IR', english: 'Iran',                                   deutsch: 'Iran' },
  { code: 'IS', english: 'Iceland',                                deutsch: 'Island' },
  { code: 'IT', english: 'Italy',                                  deutsch: 'Italien' },
  { code: 'JE', english: 'Jersey',                                 deutsch: 'Jersey' },
  { code: 'JM', english: 'Jamaica',                                deutsch: 'Jamaika' },
  { code: 'JO', english: 'Jordan',                                 deutsch: 'Jordanien' },
  { code: 'JP', english: 'Japan',                                  deutsch: 'Japan' },
  { code: 'KE', english: 'Kenya',                                  deutsch: 'Kenia' },
  { code: 'KG', english: 'Kyrgyzstan',                             deutsch: 'Kirgisistan' },
  { code: 'KH', english: 'Cambodia',                               deutsch: 'Kambodscha' },
  { code: 'KI', english: 'Kiribati',                               deutsch: 'Kiribati' },
  { code: 'KM', english: 'Comoros',                                deutsch: 'Komoren' },
  { code: 'KN', english: 'St. Kitts & Nevis',                      deutsch: 'St. Kitts und Nevis' },
  { code: 'KP', english: 'North Korea',                            deutsch: 'Nordkorea' },
  { code: 'KR', english: 'South Korea',                            deutsch: 'Südkorea' },
  { code: 'KW', english: 'Kuwait',                                 deutsch: 'Kuwait' },
  { code: 'KY', english: 'Cayman Islands',                         deutsch: 'Kaimaninseln' },
  { code: 'KZ', english: 'Kazakhstan',                             deutsch: 'Kasachstan' },
  { code: 'LA', english: 'Laos',                                   deutsch: 'Laos' },
  { code: 'LB', english: 'Lebanon',                                deutsch: 'Libanon' },
  { code: 'LC', english: 'St. Lucia',                              deutsch: 'St. Lucia' },
  { code: 'LI', english: 'Liechtenstein',                          deutsch: 'Liechtenstein' },
  { code: 'LK', english: 'Sri Lanka',                              deutsch: 'Sri Lanka' },
  { code: 'LR', english: 'Liberia',                                deutsch: 'Liberia' },
  { code: 'LS', english: 'Lesotho',                                deutsch: 'Lesotho' },
  { code: 'LT', english: 'Lithuania',                              deutsch: 'Litauen' },
  { code: 'LU', english: 'Luxembourg',                             deutsch: 'Luxemburg' },
  { code: 'LV', english: 'Latvia',                                 deutsch: 'Lettland' },
  { code: 'LY', english: 'Libya',                                  deutsch: 'Libyen' },
  { code: 'MA', english: 'Morocco',                                deutsch: 'Marokko' },
  { code: 'MC', english: 'Monaco',                                 deutsch: 'Monaco' },
  { code: 'MD', english: 'Moldova',                                deutsch: 'Republik Moldau' },
  { code: 'ME', english: 'Montenegro',                             deutsch: 'Montenegro' },
  { code: 'MF', english: 'St. Martin',                             deutsch: 'St. Martin' },
  { code: 'MG', english: 'Madagascar',                             deutsch: 'Madagaskar' },
  { code: 'MH', english: 'Marshall Islands',                       deutsch: 'Marshallinseln' },
  { code: 'MK', english: 'Macedonia',                              deutsch: 'Mazedonien' },
  { code: 'ML', english: 'Mali',                                   deutsch: 'Mali' },
  { code: 'MM', english: 'Myanmar (Burma)',                        deutsch: 'Myanmar' },
  { code: 'MN', english: 'Mongolia',                               deutsch: 'Mongolei' },
  { code: 'MO', english: 'Macau SAR China',                        deutsch: 'Sonderverwaltungsregion Macau' },
  { code: 'MP', english: 'Northern Mariana Islands',               deutsch: 'Nördliche Marianen' },
  { code: 'MQ', english: 'Martinique',                             deutsch: 'Martinique' },
  { code: 'MR', english: 'Mauritania',                             deutsch: 'Mauretanien' },
  { code: 'MS', english: 'Montserrat',                             deutsch: 'Montserrat' },
  { code: 'MT', english: 'Malta',                                  deutsch: 'Malta' },
  { code: 'MU', english: 'Mauritius',                              deutsch: 'Mauritius' },
  { code: 'MV', english: 'Maldives',                               deutsch: 'Malediven' },
  { code: 'MW', english: 'Malawi',                                 deutsch: 'Malawi' },
  { code: 'MX', english: 'Mexico',                                 deutsch: 'Mexiko' },
  { code: 'MY', english: 'Malaysia',                               deutsch: 'Malaysia' },
  { code: 'MZ', english: 'Mozambique',                             deutsch: 'Mosambik' },
  { code: 'NA', english: 'Namibia',                                deutsch: 'Namibia' },
  { code: 'NC', english: 'New Caledonia',                          deutsch: 'Neukaledonien' },
  { code: 'NE', english: 'Niger',                                  deutsch: 'Niger' },
  { code: 'NF', english: 'Norfolk Island',                         deutsch: 'Norfolkinsel' },
  { code: 'NG', english: 'Nigeria',                                deutsch: 'Nigeria' },
  { code: 'NI', english: 'Nicaragua',                              deutsch: 'Nicaragua' },
  { code: 'NL', english: 'Netherlands',                            deutsch: 'Niederlande' },
  { code: 'NO', english: 'Norway',                                 deutsch: 'Norwegen' },
  { code: 'NP', english: 'Nepal',                                  deutsch: 'Nepal' },
  { code: 'NR', english: 'Nauru',                                  deutsch: 'Nauru' },
  { code: 'NU', english: 'Niue',                                   deutsch: 'Niue' },
  { code: 'NZ', english: 'New Zealand',                            deutsch: 'Neuseeland' },
  { code: 'OM', english: 'Oman',                                   deutsch: 'Oman' },
  { code: 'PA', english: 'Panama',                                 deutsch: 'Panama' },
  { code: 'PE', english: 'Peru',                                   deutsch: 'Peru' },
  { code: 'PF', english: 'French Polynesia',                       deutsch: 'Französisch-Polynesien' },
  { code: 'PG', english: 'Papua New Guinea',                       deutsch: 'Papua-Neuguinea' },
  { code: 'PH', english: 'Philippines',                            deutsch: 'Philippinen' },
  { code: 'PK', english: 'Pakistan',                               deutsch: 'Pakistan' },
  { code: 'PL', english: 'Poland',                                 deutsch: 'Polen' },
  { code: 'PM', english: 'St. Pierre & Miquelon',                  deutsch: 'St. Pierre und Miquelon' },
  { code: 'PN', english: 'Pitcairn Islands',                       deutsch: 'Pitcairninseln' },
  { code: 'PR', english: 'Puerto Rico',                            deutsch: 'Puerto Rico' },
  { code: 'PS', english: 'Palestinian Territories',                deutsch: 'Palästinensische Autonomiegebiete' },
  { code: 'PT', english: 'Portugal',                               deutsch: 'Portugal' },
  { code: 'PW', english: 'Palau',                                  deutsch: 'Palau' },
  { code: 'PY', english: 'Paraguay',                               deutsch: 'Paraguay' },
  { code: 'QA', english: 'Qatar',                                  deutsch: 'Katar' },
  { code: 'QO', english: 'Outlying Oceania',                       deutsch: 'Äußeres Ozeanien' },
  { code: 'RE', english: 'Réunion',                                deutsch: 'Réunion' },
  { code: 'RO', english: 'Romania',                                deutsch: 'Rumänien' },
  { code: 'RS', english: 'Serbia',                                 deutsch: 'Serbien' },
  { code: 'RU', english: 'Russia',                                 deutsch: 'Russland' },
  { code: 'RW', english: 'Rwanda',                                 deutsch: 'Ruanda' },
  { code: 'SA', english: 'Saudi Arabia',                           deutsch: 'Saudi-Arabien' },
  { code: 'SB', english: 'Solomon Islands',                        deutsch: 'Salomonen' },
  { code: 'SC', english: 'Seychelles',                             deutsch: 'Seychellen' },
  { code: 'SD', english: 'Sudan',                                  deutsch: 'Sudan' },
  { code: 'SE', english: 'Sweden',                                 deutsch: 'Schweden' },
  { code: 'SG', english: 'Singapore',                              deutsch: 'Singapur' },
  { code: 'SH', english: 'St. Helena',                             deutsch: 'St. Helena' },
  { code: 'SI', english: 'Slovenia',                               deutsch: 'Slowenien' },
  { code: 'SJ', english: 'Svalbard & Jan Mayen',                   deutsch: 'Spitzbergen und Jan Mayen' },
  { code: 'SK', english: 'Slovakia',                               deutsch: 'Slowakei' },
  { code: 'SL', english: 'Sierra Leone',                           deutsch: 'Sierra Leone' },
  { code: 'SM', english: 'San Marino',                             deutsch: 'San Marino' },
  { code: 'SN', english: 'Senegal',                                deutsch: 'Senegal' },
  { code: 'SO', english: 'Somalia',                                deutsch: 'Somalia' },
  { code: 'SR', english: 'Suriname',                               deutsch: 'Suriname' },
  { code: 'SS', english: 'South Sudan',                            deutsch: 'Südsudan' },
  { code: 'ST', english: 'São Tomé & Príncipe',                    deutsch: 'São Tomé und Príncipe' },
  { code: 'SV', english: 'El Salvador',                            deutsch: 'El Salvador' },
  { code: 'SX', english: 'Sint Maarten',                           deutsch: 'Sint Maarten' },
  { code: 'SY', english: 'Syria',                                  deutsch: 'Syrien' },
  { code: 'SZ', english: 'Swaziland',                              deutsch: 'Swasiland' },
  { code: 'TA', english: 'Tristan da Cunha',                       deutsch: 'Tristan da Cunha' },
  { code: 'TC', english: 'Turks & Caicos Islands',                 deutsch: 'Turks- und Caicosinseln' },
  { code: 'TD', english: 'Chad',                                   deutsch: 'Tschad' },
  { code: 'TF', english: 'French Southern Territories',            deutsch: 'Französische Süd- und Antarktisgebiete' },
  { code: 'TG', english: 'Togo',                                   deutsch: 'Togo' },
  { code: 'TH', english: 'Thailand',                               deutsch: 'Thailand' },
  { code: 'TJ', english: 'Tajikistan',                             deutsch: 'Tadschikistan' },
  { code: 'TK', english: 'Tokelau',                                deutsch: 'Tokelau' },
  { code: 'TL', english: 'Timor-Leste',                            deutsch: 'Timor-Leste' },
  { code: 'TM', english: 'Turkmenistan',                           deutsch: 'Turkmenistan' },
  { code: 'TN', english: 'Tunisia',                                deutsch: 'Tunesien' },
  { code: 'TO', english: 'Tonga',                                  deutsch: 'Tonga' },
  { code: 'TR', english: 'Turkey',                                 deutsch: 'Türkei' },
  { code: 'TT', english: 'Trinidad & Tobago',                      deutsch: 'Trinidad und Tobago' },
  { code: 'TV', english: 'Tuvalu',                                 deutsch: 'Tuvalu' },
  { code: 'TW', english: 'Taiwan',                                 deutsch: 'Taiwan' },
  { code: 'TZ', english: 'Tanzania',                               deutsch: 'Tansania' },
  { code: 'UA', english: 'Ukraine',                                deutsch: 'Ukraine' },
  { code: 'UG', english: 'Uganda',                                 deutsch: 'Uganda' },
  { code: 'UM', english: 'U.S. Outlying Islands',                  deutsch: 'Amerikanische Überseeinseln' },
  { code: 'US', english: 'United States',                          deutsch: 'Vereinigte Staaten' },
  { code: 'UY', english: 'Uruguay',                                deutsch: 'Uruguay' },
  { code: 'UZ', english: 'Uzbekistan',                             deutsch: 'Usbekistan' },
  { code: 'VA', english: 'Vatican City',                           deutsch: 'Vatikanstadt' },
  { code: 'VC', english: 'St. Vincent & Grenadines',               deutsch: 'St. Vincent und die Grenadinen' },
  { code: 'VE', english: 'Venezuela',                              deutsch: 'Venezuela' },
  { code: 'VG', english: 'British Virgin Islands',                 deutsch: 'Britische Jungferninseln' },
  { code: 'VI', english: 'U.S. Virgin Islands',                    deutsch: 'Amerikanische Jungferninseln' },
  { code: 'VN', english: 'Vietnam',                                deutsch: 'Vietnam' },
  { code: 'VU', english: 'Vanuatu',                                deutsch: 'Vanuatu' },
  { code: 'WF', english: 'Wallis & Futuna',                        deutsch: 'Wallis und Futuna' },
  { code: 'WS', english: 'Samoa',                                  deutsch: 'Samoa' },
  { code: 'XK', english: 'Kosovo',                                 deutsch: 'Kosovo' },
  { code: 'YE', english: 'Yemen',                                  deutsch: 'Jemen' },
  { code: 'YT', english: 'Mayotte',                                deutsch: 'Mayotte' },
  { code: 'ZA', english: 'South Africa',                           deutsch: 'Südafrika' },
  { code: 'ZM', english: 'Zambia',                                 deutsch: 'Sambia' },
  { code: 'ZW', english: 'Zimbabwe',                               deutsch: 'Simbabwe' },
];
